name: Check code

on:
  # Runs on pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Check job
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'
          cache: npm
      - name: Install dependencies
        run: npm ci --include=dev
      - name: Env setup
        run: echo "PUBLIC_VERSION=$(git rev-parse --short HEAD)" > .env
      - name: Check
        run: npm run check
